# Generated by Django 5.2.1 on 2025-05-14 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FingerPrintData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('passport', models.CharField(max_length=9, unique=True, verbose_name='Passport number')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone number')),
                ('fingerprint_template', models.BinaryField(verbose_name='Fingerprint data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fingerprint data',
                'verbose_name_plural': 'Fingerprint data',
                'indexes': [models.Index(fields=['passport'], name='users_finge_passpor_0c2250_idx'), models.Index(fields=['phone'], name='users_finge_phone_f230d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScanningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('similarity', models.FloatField(default=0)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('device_info', models.CharField(max_length=255, null=True)),
                ('fingerprint_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanning_logs', to='users.fingerprintdata')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
